language: node_js
os: linux
dist: bionic
node_js:
  12
before_script:
  - npm install
env:
  global:
    secure: cowLFL38k7cCKbgk2KgTYxIcKMnKdiqzV9c2Uedh8M86/WcwkM9rLjaYVdbylsNGUzCuV5DixzgRKP6ZKq4D0U2zkuWecV/IoPiKHaV46zb0wnV/DJGqwi5XoPnjFuug8AoLx/3/dhkEONMIpz/smTjU6LXevG4+XcavFZjgiQBPibsDn2ax3E1qrufs5sHgHMGLeBZA2DeRAzW8qOMpRAhPFnpep4qeA34dkCjHuj9pVz04PO1sDY0kTl5J1K80yLDfwxB64Qt5aOt1Cwc/g259TBlKK9EUzyKzUQhS7u/dxZUEhxDwr9HaBvTUsaDeldXLRwK4OHP4Rs4POYInfH+UIn9PpPBw0jGoI4hPOc8fa3bTJCFhx70S+/90vRwFRDp5r2ZMOyqVlsGgDPqeuHjJ5+DOS/XjIRXvDWjnVFJjfLN/4jwiaJKpRT99WcRmRJWOQ3JKBylyPWXDjmT2T5Eo6P7tAGm2oI3iQi/vfxmJLvYfa0dGs1I/B+DHQNBtsnXvJXdD3jwwHuse/gSIAuTx9Lcnas7pBDPq2kkbhyDg8i3MadomPIKtRdEzAyO1sboptWsa9uxANhyikNBjFJ7sVTbCLg3GGD1Yo1D0cxv0lJaaayU4oTaF3epVkMwiww7WI3MhQJ2zG3Wuc1+n7n6SXcsAQs2aIY3XulMHDUE=
script: npm run build
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  strategy: git
  local_dir: webapp
  on:
    branch: develop
  edge: true