name: Post Release Process
on:
    release:
        types: [published]
concurrency: ${{ github.workflow }}
jobs:
    release:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-workflow.yml@develop
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
